name: Build Website
on:
  repository_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build 🔧
        env:
          API_URL: ${{ secrets.API_URL }}
        run: pnpm build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
